### ISSUE TITLE
Feature Request - Remove search bar & App Suggestions

### ISSUE THREAD

**Issue by mohagan9** [CallToPower/BlissLauncher#1]
Thanks for this, nice to be able to use a custom weather widget over the default!

Would it be possible to remove the search bar along the top and app suggestions box as well? 

Not sure if that's in line with what you were going for, but it'd be nice to have only the EDIT button so that the widget page is entirely customizable.

**Comment by CallToPower** [comment]
Sure, that should be possible, I'll think about it and will look into it if there's time.

**Comment by CallToPower** [comment]
Update: I made a new build and removed the search bar and the app suggestions from the widget page. Feel free to test it:
https://github.com/CallToPower/BlissLauncher/releases/tag/1.3.3-build-1
