### ISSUE TITLE
Witgets update request ❤️

### ISSUE THREAD

**Issue by RaphaelRadl** [CallToPower/BlissLauncher#3]
Hi @CallToPower 

I am using / e / OS on my Galaxy S10e and discovered a bug on the Witget page. I think the design of the icons is really nice because it always reminds me of Classic IOS 6. However, a nicer solution would be to use New Witgets in the style of IOS 15!

![Screenshot_20211018-095810_Bliss_Starter](https://user-images.githubusercontent.com/75857073/137693348-e4e6c497-a548-4c67-b20a-3f581c1604f1.png)
#

**Comment by CallToPower** [comment]
Hi @RaphaelRadl,
great seeing someone using /e/OS and the BlissLauncher!
This Github repository, however, is not the official /e/OS BlissLauncher repository. I merely forked the original one to change a few things (e.g. double tap to sleep) on my own.
Your request surely is a valid one, but to get it into the official code base and build, the authors of the BlissLauncher have to review and implement it.
Please go over to the official repository at https://gitlab.e.foundation/e/apps/BlissLauncher/ and state your request.
Thanks!
